dist: xenial
language: csharp
solution: eform-InstallationCheckingBase/Microting.InstallationCheckingBase.sln
mono: none
dotnet: 3.1.101
addons:
  chrome: stable
  mariadb: '10.5'
script:
  - sudo mysql -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password'
  - dotnet restore
  - dotnet build Microting.InstallationCheckingBase.sln
  - dotnet test -v n Microting.InstallationCheckingBase.Tests/Microting.InstallationCheckingBase.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.InstallationCheckingBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-installationchecking-base/Microting.InstallationCheckingBase/artifacts/Microting.InstallationCheckingBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
